// All Paladin tuning and presentation metadata lives here.
export const PALADIN_CONFIG = {
  id: 'paladin',
  name: 'Paladin',
  role: 'Melee / self-sustain',
  maxHealth: 140,
  moveSpeed: 230,
  radius: 20,
  spawn: { x: 0.5, y: 0.68 },
  primaryResource: 'mana',
  visual: {
    body: '#e4b64e',
    core: '#fff3bd',
    shield: '#ffe68a',
    holy: '#ffd86b',
  },
  resources: {
    mana: {
      name: 'Mana',
      max: 100,
      start: 100,
      color: '#5477df',
    },
  },
  abilities: {
    strike: {
      name: 'Crusader Strike',
      description: 'Strike the boss in melee. Deals light damage and restores a small amount of mana.',
      icon: './assets/classes/paladin/abilities/crusader-strike.svg',
      cooldown: 1.25,
      damage: 24,
      meleeRange: 145,
      manaRestore: 4,
      castDisplay: 'Instant · melee range',
    },
    brand: {
      name: 'Sacred Brand',
      description: 'Long cast that adds an independent holy damage-over-time stack to the target. Multiple Brands can overlap.',
      icon: './assets/classes/paladin/abilities/sacred-brand.svg',
      cooldown: 0,
      castTime: 2.4,
      manaCost: 45,
      castDisplay: '2.4 sec cast · 45 mana · stacks',
      dot: {
        duration: 12,
        tickEvery: 1.5,
        damagePerTick: 14,
      },
    },
    heal: {
      name: 'Holy Light',
      description: 'Restore a large amount of health after a direct cast.',
      icon: './assets/classes/paladin/abilities/holy-light.svg',
      cooldown: 0,
      castTime: 1.6,
      manaCost: 40,
      heal: 55,
      castDisplay: '1.6 sec cast · 40 mana',
    },
    meditation: {
      name: 'Divine Meditation',
      description: 'Shield yourself from all damage while casting. Completing the cast restores a large amount of mana.',
      icon: './assets/classes/paladin/abilities/divine-meditation.svg',
      cooldown: 50,
      castTime: 3,
      manaRestore: 75,
      castDisplay: '3.0 sec cast · immune while casting',
    },
  },
};
