export const LIVING_LIBRARY_CONFIG = {
  id: 'living-library',
  name: 'The Living Library',
  arena: {
    width: 1850,
    height: 1120,
    playerSpawn: { x: 0.5, y: 0.8 },
  },
  maxHealth: 2600,
  radius: 52,
  position: { x: 0.5, y: 0.28 },
  visual: {
    body: '#5f4c80',
    core: '#e6d9ff',
    ink: '#b99cff',
    warning: '#ffd36a',
    danger: '#ff6b77',
    silence: '#74d99a',
  },
  encounter: {
    openingDelay: 2.2,
    previewTime: 2.8,
    delayBetweenMechanics: 1.35,
    basePulseInterval: 8.5,
    basePulseDamage: 11,
    damagePerDestroyedBook: 0.18,
    castSpeedPerDestroyedBook: 0.09,
    minCastMultiplier: 0.58,
  },
  books: {
    maxHealth: 250,
    radius: 30,
    entries: {
      ring: {
        name: 'Codex of Binding',
        mechanicName: 'Binding Ring',
        pageLabel: 'RING',
        color: '#65b8ff',
        position: { x: 0.22, y: 0.34 },
      },
      beam: {
        name: 'Mirror Grimoire',
        mechanicName: 'Reflected Passage',
        pageLabel: 'BEAM',
        color: '#c27cff',
        position: { x: 0.78, y: 0.34 },
      },
      blast: {
        name: 'Ember Compendium',
        mechanicName: 'Burning Margins',
        pageLabel: 'BLAST',
        color: '#ff9b52',
        position: { x: 0.25, y: 0.68 },
      },
      silence: {
        name: 'Null Lexicon',
        mechanicName: 'Unwritten Word',
        pageLabel: 'SILENCE',
        color: '#63d791',
        position: { x: 0.75, y: 0.68 },
      },
    },
  },
  mechanics: {
    ring: {
      castTime: 1.7,
      damage: 34,
      startRadius: 85,
      endRadius: 720,
      width: 42,
      duration: 2.25,
    },
    beam: {
      castTime: 1.8,
      damage: 24,
      duration: 4.2,
      length: 920,
      halfWidth: 27,
      rotationSpeed: 0.95,
      hitCooldown: 0.9,
    },
    blast: {
      castTime: 1.9,
      damage: 38,
      count: 4,
      radius: 78,
      delay: 1.8,
      spread: 500,
    },
    silence: {
      castTime: 1.65,
      count: 3,
      radius: 120,
      duration: 5.4,
    },
  },
  sequence: ['ring', 'blast', 'beam', 'silence', 'blast', 'ring', 'silence', 'beam'],
};
