// All Monk tuning and presentation metadata lives here.
export const MONK_CONFIG = {
  id: 'monk',
  name: 'Monk',
  role: 'Melee / combo fighter',
  maxHealth: 125,
  moveSpeed: 250,
  radius: 19,
  spawn: { x: 0.5, y: 0.68 },
  visual: {
    body: '#d7c28a',
    core: '#fff3c9',
    blue: '#52a9ff',
    green: '#59d58a',
    red: '#ff675f',
    shield: '#87caff',
  },
  abilities: {
    blueStrike: {
      name: 'Azure Palm',
      description: 'Low-cooldown melee strike. BLUE → GREEN grants a shield. BLUE → RED grants a short speed boost.',
      icon: './assets/classes/monk/abilities/azure-palm.svg',
      cooldown: 1.4,
      damage: 25,
      meleeRange: 145,
      color: 'blue',
      castDisplay: 'Instant · melee range',
    },
    greenStrike: {
      name: 'Jade Strike',
      description: 'Low-cooldown melee strike. GREEN → BLUE instantly heals. GREEN → RED starts a heal over time.',
      icon: './assets/classes/monk/abilities/jade-strike.svg',
      cooldown: 1.6,
      damage: 23,
      meleeRange: 145,
      color: 'green',
      castDisplay: 'Instant · melee range',
    },
    redStrike: {
      name: 'Crimson Kick',
      description: 'Low-cooldown melee strike. RED → BLUE fires an energy ball. RED → GREEN applies a damage-over-time effect.',
      icon: './assets/classes/monk/abilities/crimson-kick.svg',
      cooldown: 1.8,
      damage: 29,
      meleeRange: 150,
      color: 'red',
      castDisplay: 'Instant · melee range',
    },
    roll: {
      name: 'Flowing Roll',
      description: 'Roll a long distance in your held movement direction. If stationary, roll away from the boss.',
      icon: './assets/classes/monk/abilities/flowing-roll.svg',
      cooldown: 7,
      distance: 260,
      castDisplay: 'Instant movement',
    },
  },
  combos: {
    blueGreen: {
      name: 'Azure Guard',
      shield: 42,
      duration: 6,
    },
    blueRed: {
      name: 'Windstep',
      speedMultiplier: 1.6,
      duration: 3,
    },
    greenBlue: {
      name: 'Restoring Touch',
      heal: 34,
    },
    greenRed: {
      name: 'Flowing Mending',
      duration: 6,
      tickEvery: 1,
      healPerTick: 9,
    },
    redBlue: {
      name: 'Chi Bolt',
      damage: 58,
      projectileDuration: 0.28,
    },
    redGreen: {
      name: 'Burning Meridian',
      duration: 8,
      tickEvery: 1,
      damagePerTick: 10,
    },
  },
};
