export const HUNTER_CONFIG = {
  id: 'hunter',
  name: 'Hunter',
  role: 'Ranged pet controller / fury spender',
  maxHealth: 100,
  moveSpeed: 265,
  radius: 18,
  spawn: { x: 0.5, y: 0.72 },
  visual: {
    body: '#7fb56b',
    core: '#d9efb6',
    frenzy: '#f5a85b',
    arrow: '#d7f0bc',
  },
  primaryResource: 'fury',
  resources: {
    fury: {
      name: 'Fury',
      max: 100,
      start: 0,
      color: '#d7793f',
    },
  },
  pet: {
    name: 'Tiger',
    maxHealth: 90,
    radius: 18,
    homeOffset: { x: 38, y: 26 },
    leapDuration: 0.24,
    engagedOffset: 14,
    autoAttackEvery: 1.15,
    autoAttackDamage: 16,
    visual: {
      body: '#d88935',
      stripe: '#4d2f20',
      core: '#f5c16e',
    },
  },
  abilities: {
    bowShot: {
      name: 'Bow Shot',
      description: 'Fire a basic arrow for 26 damage and generate 18 Fury.',
      icon: './assets/classes/hunter/abilities/bow-shot.svg',
      castTime: 0.65,
      cooldown: 0.4,
      damage: 26,
      furyGain: 18,
    },
    frenzy: {
      name: 'Frenzy',
      description: 'Spend 60 Fury. Hunter and Tiger deal 60% more damage for 8 sec.',
      icon: './assets/classes/hunter/abilities/frenzy.svg',
      cooldown: 0,
      furyCost: 60,
      duration: 8,
      damageMultiplier: 1.6,
      resource: 'fury',
      castDisplay: 'Instant · costs 60 Fury',
    },
    bandage: {
      name: 'Bandage',
      description: 'Prime Bandage, then press 1 for Hunter or 2 for Tiger. Channel healing and stop if you move.',
      icon: './assets/classes/hunter/abilities/bandage.svg',
      cooldown: 0,
      duration: 5,
      tickEvery: 0.5,
      maxHealingPercent: 0.5,
      castDisplay: 'Targeted channel · press 1 or 2',
    },
    petAttack: {
      name: 'Tiger: Pounce',
      description: 'Command the Tiger to leap to the boss, deal damage, and keep attacking until recalled.',
      icon: './assets/classes/hunter/abilities/tiger-pounce.svg',
      cooldown: 2,
      pounceDamage: 24,
    },
    petReturn: {
      name: 'Tiger: Return',
      description: 'Command the Tiger to leap back to you to avoid danger.',
      icon: './assets/classes/hunter/abilities/tiger-return.svg',
      cooldown: 1,
    },
    revivePet: {
      name: 'Revive Tiger',
      description: 'Revive your Tiger after a long cast. You may move while casting, but at 45% movement speed.',
      icon: './assets/classes/hunter/abilities/revive-tiger.svg',
      cooldown: 0,
      castTime: 6,
      moveSpeedMultiplier: 0.45,
      castDisplay: '6.0 sec mobile cast · movement slowed',
    },
  },
};
