// All Choir encounter tuning and note/chord definitions live here.
export const CHOIR_CONFIG = {
  id: 'choir',
  name: 'The Choir',
  arena: {
    width: 1850,
    height: 1120,
    playerSpawn: { x: 0.5, y: 0.78 },
  },
  maxHealth: 2600,
  radius: 34,
  position: { x: 0.5, y: 0.34 },
  visual: {
    body: '#d9d0ee',
    core: '#fff7d6',
    danger: '#ff6478',
    warning: '#ffd36d',
    silence: '#67d79b',
  },
  encounter: {
    openingDelay: 2.0,
    delayBetweenSongs: 1.35,
    phaseTwoHealthPercent: 68,
    phaseThreeHealthPercent: 36,
  },
  heads: [
    { id: 'c', name: 'Cantor C', note: 'C', frequency: 261.63, color: '#69b7ff', offset: { x: -175, y: -10 } },
    { id: 'd', name: 'Cantor D', note: 'D', frequency: 293.66, color: '#c58cff', offset: { x: -60, y: -70 } },
    { id: 'e', name: 'Cantor E', note: 'E', frequency: 329.63, color: '#ff9b67', offset: { x: 60, y: -70 } },
    { id: 'f', name: 'Cantor F', note: 'F', frequency: 349.23, color: '#78dfa5', offset: { x: 175, y: -10 } },
  ],
  notes: {
    c: {
      name: 'Resonant Ring',
      mechanic: 'ring',
      castTime: 1.7,
      ringStartRadius: 80,
      ringEndRadius: 760,
      ringDuration: 2.8,
      ringWidth: 42,
      damage: 34,
    },
    d: {
      name: 'Sweeping Hymn',
      mechanic: 'beam',
      castTime: 1.8,
      beamDuration: 4.2,
      beamLength: 880,
      beamHalfWidth: 32,
      rotationSpeed: 0.95,
      damage: 24,
      hitCooldown: 0.7,
    },
    e: {
      name: 'Falling Cadence',
      mechanic: 'ground',
      castTime: 1.6,
      count: 5,
      radius: 72,
      delay: 1.7,
      damage: 31,
    },
    f: {
      name: 'Muted Verse',
      mechanic: 'silence',
      castTime: 1.5,
      count: 3,
      radius: 105,
      duration: 5.5,
    },
  },
  phaseOneSequence: [
    { name: 'C', notes: ['c'] },
    { name: 'D', notes: ['d'] },
    { name: 'E', notes: ['e'] },
    { name: 'F', notes: ['f'] },
  ],
  phaseTwoSequence: [
    { name: 'Bright Third', notes: ['c', 'e'] },
    { name: 'Veiled Fourth', notes: ['d', 'f'] },
    { name: 'Burning Second', notes: ['d', 'e'] },
    { name: 'Hollow Fourth', notes: ['c', 'f'] },
  ],
  phaseThreeSequence: [
    { name: 'Choir Major', notes: ['c', 'd', 'e'] },
    { name: 'Choir Minor', notes: ['d', 'e', 'f'] },
    { name: 'Final Chord', notes: ['c', 'd', 'e', 'f'] },
  ],
};
