export const ROGUE_CONFIG = {
  id: 'rogue',
  name: 'Rogue',
  role: 'Melee / poison skirmisher',
  maxHealth: 105,
  moveSpeed: 285,
  radius: 17,
  spawn: { x: 0.5, y: 0.68 },
  visual: {
    body: '#7861a8',
    core: '#ddd3ff',
    poison: '#73df78',
    vial: '#8cff86',
    sprint: '#d0c2ff',
    execute: '#d5b1ff',
    reclaim: '#7fffb0',
  },
  poison: {
    weaponDuration: 18,
    targetDuration: 8,
    tickEvery: 1,
    damagePerTick: 10,
    sprintCooldownReductionPerTick: 1,
  },
  comboPoints: {
    max: 4,
    gainPerPoisonedSlash: 1,
  },
  vial: {
    pickupRadius: 42,
    radius: 15,
    arenaMargin: 110,
  },
  abilities: {
    slash: {
      name: 'Venom Slash',
      description: 'A fast melee slash. Hitting an enemy that is already poisoned generates 1 Combo Point. Poisoned weapons apply or refresh poison.',
      icon: './assets/classes/rogue/abilities/venom-slash.svg',
      cooldown: 0.75,
      damage: 32,
      meleeRange: 145,
      castDisplay: 'Instant · melee range · builds Combo Points',
    },
    vial: {
      name: 'Prepare Poison',
      description: 'Cast to throw a poison vial to a random playable location. Pick it up to poison your weapons for 18 sec.',
      icon: './assets/classes/rogue/abilities/poison-vial.svg',
      cooldown: 14,
      castTime: 1.4,
      castDisplay: '1.4 sec cast · creates pickup',
    },
    sprint: {
      name: 'Sprint',
      description: 'Greatly increase movement speed. Every poison damage tick reduces Sprint cooldown by 1 sec.',
      icon: './assets/classes/rogue/abilities/sprint.svg',
      cooldown: 18,
      duration: 4,
      speedMultiplier: 1.75,
      castDisplay: 'Instant · poison ticks reduce cooldown',
    },
    reclaim: {
      name: 'Venom Reclaim',
      description: 'Consume the active poison on your selected enemy to restore 40 health. Does not consume your weapon-poison buff.',
      icon: './assets/classes/rogue/abilities/venom-reclaim.svg',
      cooldown: 8,
      heal: 40,
      castDisplay: 'Instant · consumes target poison · heals 40',
    },
    execute: {
      name: 'Execute',
      description: 'Spend 4 Combo Points to deliver a devastating melee finisher. Can only be used on a poisoned enemy.',
      icon: './assets/classes/rogue/abilities/execute.svg',
      cooldown: 0.8,
      damage: 115,
      meleeRange: 145,
      comboPointCost: 4,
      castDisplay: 'Instant · melee range · costs 4 Combo Points',
    },
  },
};
