export const ROGUE_CONFIG = {
  id: 'rogue',
  name: 'Rogue',
  role: 'Melee / poison skirmisher',
  maxHealth: 105,
  moveSpeed: 285,
  radius: 17,
  spawn: { x: 0.5, y: 0.68 },
  visual: {
    body: '#7861a8',
    core: '#ddd3ff',
    poison: '#73df78',
    vial: '#8cff86',
    sprint: '#d0c2ff',
  },
  poison: {
    weaponDuration: 18,
    targetDuration: 8,
    tickEvery: 1,
    damagePerTick: 10,
    lifestealPercent: 0.5,
    sprintCooldownReductionPerTick: 1,
  },
  vial: {
    pickupRadius: 42,
    radius: 15,
    arenaMargin: 110,
  },
  abilities: {
    slash: {
      name: 'Venom Slash',
      description: 'A fast melee slash. While your weapons are poisoned, the hit poisons the boss.',
      icon: './assets/classes/rogue/abilities/venom-slash.svg',
      cooldown: 0.75,
      damage: 32,
      meleeRange: 145,
      castDisplay: 'Instant · melee range',
    },
    knife: {
      name: 'Knife Throw',
      description: 'Throw a knife from range for much less damage. Poisoned weapons also poison the knife.',
      icon: './assets/classes/rogue/abilities/knife-throw.svg',
      cooldown: 1,
      damage: 12,
      range: 650,
      projectileDuration: 0.2,
      castDisplay: 'Instant · 650 range',
    },
    vial: {
      name: 'Prepare Poison',
      description: 'Cast to throw a poison vial to a random playable location. Pick it up to poison your weapons for 18 sec.',
      icon: './assets/classes/rogue/abilities/poison-vial.svg',
      cooldown: 14,
      castTime: 1.4,
      castDisplay: '1.4 sec cast · creates pickup',
    },
    sprint: {
      name: 'Sprint',
      description: 'Greatly increase movement speed. Every poison damage tick reduces Sprint cooldown by 1 sec.',
      icon: './assets/classes/rogue/abilities/sprint.svg',
      cooldown: 18,
      duration: 4,
      speedMultiplier: 1.75,
      castDisplay: 'Instant · poison ticks reduce cooldown',
    },
  },
};
