// All Druid tuning and presentation metadata lives here.
const FORM_ABILITIES = {
  bear: ['bearMaul', 'bearEarthbreaker'],
  monkey: ['monkeyVault', 'monkeyRetreat'],
  puma: ['pumaClaw', 'pumaRake'],
  panda: ['pandaMend', 'pandaRenewal'],
};

export const DRUID_CONFIG = {
  id: 'druid',
  name: 'Druid',
  role: 'Shapeshifter / adaptive',
  maxHealth: 115,
  moveSpeed: 245,
  radius: 19,
  spawn: { x: 0.5, y: 0.68 },
  visual: {
    caster: '#9dcf8a',
    bear: '#9b7754',
    monkey: '#e1aa5d',
    puma: '#8c72c6',
    panda: '#d9dde4',
    core: '#efffe7',
  },
  forms: {
    bear: { name: 'Bear Form', icon: './assets/classes/druid/abilities/bear-form.svg', abilities: FORM_ABILITIES.bear },
    monkey: { name: 'Monkey Form', icon: './assets/classes/druid/abilities/monkey-form.svg', abilities: FORM_ABILITIES.monkey },
    puma: { name: 'Puma Form', icon: './assets/classes/druid/abilities/puma-form.svg', abilities: FORM_ABILITIES.puma },
    panda: { name: 'Panda Form', icon: './assets/classes/druid/abilities/panda-form.svg', abilities: FORM_ABILITIES.panda },
  },
  abilities: {
    bearForm: {
      name: 'Bear Form',
      description: 'Shapeshift into Bear Form and gain access to two heavy, long-cooldown attacks.',
      icon: './assets/classes/druid/abilities/bear-form.svg',
      cooldown: 0,
      castDisplay: 'Instant shapeshift',
      form: 'bear',
    },
    monkeyForm: {
      name: 'Monkey Form',
      description: 'Shapeshift into Monkey Form and gain access to two movement abilities.',
      icon: './assets/classes/druid/abilities/monkey-form.svg',
      cooldown: 0,
      castDisplay: 'Instant shapeshift',
      form: 'monkey',
    },
    pumaForm: {
      name: 'Puma Form',
      description: 'Shapeshift into Puma Form and gain access to two fast melee attacks.',
      icon: './assets/classes/druid/abilities/puma-form.svg',
      cooldown: 0,
      castDisplay: 'Instant shapeshift',
      form: 'puma',
    },
    pandaForm: {
      name: 'Panda Form',
      description: 'Shapeshift into Panda Form and gain access to two healing abilities.',
      icon: './assets/classes/druid/abilities/panda-form.svg',
      cooldown: 0,
      castDisplay: 'Instant shapeshift',
      form: 'panda',
    },
    bearMaul: {
      name: 'Crushing Maul',
      description: 'A heavy melee strike with a long cooldown.',
      icon: './assets/classes/druid/abilities/crushing-maul.svg',
      cooldown: 7,
      damage: 70,
      meleeRange: 150,
      castDisplay: 'Instant · melee range',
    },
    bearEarthbreaker: {
      name: 'Earthbreaker',
      description: 'Smash the ground for a very heavy melee hit. Long cooldown.',
      icon: './assets/classes/druid/abilities/earthbreaker.svg',
      cooldown: 12,
      damage: 105,
      meleeRange: 165,
      castDisplay: 'Instant · melee range',
    },
    monkeyVault: {
      name: 'Primal Vault',
      description: 'Leap rapidly in your current movement direction. If stationary, leap toward the boss.',
      icon: './assets/classes/druid/abilities/primal-vault.svg',
      cooldown: 5,
      distance: 240,
      castDisplay: 'Instant movement',
    },
    monkeyRetreat: {
      name: 'Branchbound Retreat',
      description: 'Leap directly away from the boss to create distance.',
      icon: './assets/classes/druid/abilities/branchbound-retreat.svg',
      cooldown: 8,
      distance: 300,
      castDisplay: 'Instant movement',
    },
    pumaClaw: {
      name: 'Puma Claw',
      description: 'Fast melee strike with a very short cooldown.',
      icon: './assets/classes/druid/abilities/puma-claw.svg',
      cooldown: 1.2,
      damage: 30,
      meleeRange: 145,
      castDisplay: 'Instant · melee range',
    },
    pumaRake: {
      name: 'Rending Rake',
      description: 'A stronger quick melee attack with a short cooldown.',
      icon: './assets/classes/druid/abilities/rending-rake.svg',
      cooldown: 2.6,
      damage: 46,
      meleeRange: 150,
      castDisplay: 'Instant · melee range',
    },
    pandaMend: {
      name: 'Soothing Paw',
      description: 'Instantly restore a moderate amount of health.',
      icon: './assets/classes/druid/abilities/soothing-paw.svg',
      cooldown: 5,
      heal: 38,
      castDisplay: 'Instant heal',
    },
    pandaRenewal: {
      name: 'Bamboo Renewal',
      description: 'Heal yourself over time for 54 health over 6 seconds.',
      icon: './assets/classes/druid/abilities/bamboo-renewal.svg',
      cooldown: 10,
      duration: 6,
      tickEvery: 1,
      healPerTick: 9,
      castDisplay: 'Instant · heal over time',
    },
  },
};
