// All Bellkeeper encounter tuning, bell order, and arena settings live here.
export const BELLKEEPER_CONFIG = {
  id: 'bellkeeper',
  name: 'The Bellkeeper',
  arena: {
    width: 1850,
    height: 1120,
    playerSpawn: { x: 0.5, y: 0.82 },
  },
  maxHealth: 2800,
  radius: 58,
  position: { x: 0.5, y: 0.28 },
  visual: {
    body: '#8f8172',
    armor: '#c7b28e',
    core: '#fff0b8',
    danger: '#ff665e',
    warning: '#ffd36a',
    silence: '#6bd6a0',
    projectile: '#f3d382',
    target: '#fff2ae',
  },
  bells: {
    interactionRange: 155,
    maxHealth: 240,
    order: ['quickening', 'reversal', 'silence', 'wrath'],
    entries: {
      quickening: {
        name: 'Quickening Bell',
        shortName: 'QUICKENING',
        position: { x: 0.18, y: 0.23 },
        color: '#66c7ff',
        description: 'Speeds up every Bellkeeper cast while active.',
      },
      reversal: {
        name: 'Reversal Bell',
        shortName: 'REVERSAL',
        position: { x: 0.82, y: 0.23 },
        color: '#cf8cff',
        description: 'Reverses Bellstorm projectiles so they collapse inward.',
      },
      silence: {
        name: 'Silence Bell',
        shortName: 'SILENCE',
        position: { x: 0.18, y: 0.73 },
        color: '#6bd6a0',
        description: 'Maintains silence zones that prevent ability use.',
      },
      wrath: {
        name: 'Wrath Bell',
        shortName: 'WRATH',
        position: { x: 0.82, y: 0.73 },
        color: '#ff7067',
        description: 'Enrages the Bellkeeper and increases outgoing damage.',
      },
    },
  },
  modifiers: {
    quickening: { castSpeedMultiplier: 0.72 },
    wrath: { damageMultiplier: 1.45 },
    silence: {
      radius: 112,
      zones: [
        { x: 0.36, y: 0.52 },
        { x: 0.64, y: 0.52 },
      ],
    },
  },
  encounter: {
    openingDelay: 2.0,
    delayBetweenMechanics: 1.2,
    phaseTwoHealthPercent: 65,
    phaseThreeHealthPercent: 35,
    phaseTwoDelayMultiplier: 0.78,
    phaseThreeDelayMultiplier: 0.56,
    wrongOrderDamage: 18,
    wrongOrderDamageGrowth: 5,
    wrongOrderDamageMultiplierPerStack: 0.12,
    wrongOrderCastSpeedPerStack: 0.07,
  },
  mechanics: {
    toll: {
      name: 'Cathedral Toll',
      castTime: 2.25,
      damage: 15,
      description: 'Raidwide damage. The Wrath Bell makes each toll much more dangerous.',
    },
    sweep: {
      name: 'Armored Procession',
      castTime: 2.4,
      range: 650,
      halfAngle: 0.4,
      damage: 42,
      description: 'Move out of the Bellkeeper’s frontal procession.',
    },
    bellstorm: {
      name: 'Bellstorm',
      castTime: 1.85,
      count: 8,
      overlapCount: 5,
      speed: 185,
      radius: 14,
      damage: 26,
      lifetime: 4.6,
      travelRadius: 600,
      description: 'Dodge radial bell projectiles. The Reversal Bell flips their direction.',
    },
    judgment: {
      name: 'Judgment Chimes',
      castTime: 2.1,
      count: 4,
      radius: 82,
      damage: 34,
      description: 'Move out of the marked impact circles.',
    },
    overlapHazard: {
      name: 'Consecrated Echo',
      count: 2,
      radius: 92,
      activationDelay: 1.15,
      duration: 5.0,
      tickEvery: 1.0,
      damage: 15,
    },
  },
  sequence: ['toll', 'sweep', 'bellstorm', 'judgment', 'sweep', 'toll', 'judgment', 'bellstorm'],
};
