export const FURNACE_HEART_CONFIG = {
  id: 'furnace-heart',
  name: 'The Furnace Heart',
  arena: {
    width: 1800,
    height: 1100,
    playerSpawn: { x: 0.5, y: 0.84 },
  },
  maxHealth: 2600,
  radius: 76,
  position: { x: 0.5, y: 0.5 },
  visual: {
    shell: '#5e3027',
    core: '#ff9b45',
    hotCore: '#fff0a8',
    warning: '#ffbf52',
    fire: '#ff5d32',
    critical: '#ff2f42',
    cool: '#6fc3ff',
  },
  heat: {
    max: 100,
    coolPerSecond: 6.5,
    coolingDelayAfterCast: 0.7,
    warmAt: 35,
    hotAt: 60,
    criticalAt: 85,
    minPerAbility: 4,
    maxPerAbility: 20,
    hotDamageTakenMultiplier: 1.2,
    criticalDamageTakenMultiplier: 1.35,
  },
  sectors: {
    columns: 4,
    rows: 3,
    edgePadding: 34,
    warningTime: 0.9,
    warmDuration: 4.5,
    hotDuration: 5.4,
    criticalDuration: 6.2,
    warmInterval: 4.8,
    hotInterval: 3.5,
    criticalInterval: 2.6,
    warmDamage: 10,
    hotDamage: 14,
    criticalDamage: 18,
    damageTickEvery: 0.75,
  },
  pulse: {
    name: 'Furnace Pulse',
    interval: 5.4,
    castTime: 1.35,
    baseDamage: 10,
    heatDamageScale: 0.12,
  },
};
