export const TWIN_MAGI_CONFIG = {
  id: 'twin-magi',
  name: 'The Twin Magi',
  arena: {
    width: 1900,
    height: 1150,
    playerSpawn: { x: 0.5, y: 0.78 },
  },
  maxHealth: 3200,
  radius: 44,
  position: { x: 0.5, y: 0.38 },
  visual: {
    solar: '#ffb34f',
    solarCore: '#fff0ad',
    void: '#8a68e8',
    voidCore: '#d6c8ff',
    merged: '#ef8bda',
    warning: '#ffdf6a',
  },
  encounter: {
    openingDelay: 2.0,
    phaseTwoHealthPercent: 65,
    mergeHealthPercent: 25,
    baseDelay: 3.4,
    phaseTwoDelayMultiplier: 0.76,
    empoweredDuration: 4.5,
    empoweredDamageMultiplier: 1.45,
    empoweredCastSpeedMultiplier: 0.72,
    mergeDelay: 1.8,
    finalDelay: 2.4,
  },
  magi: {
    solara: {
      name: 'Solara',
      school: 'Solar',
      color: '#ffb34f',
      core: '#fff0ad',
      position: { x: 0.32, y: 0.34 },
      sequence: ['solarLance', 'solarFlare'],
    },
    nox: {
      name: 'Nox',
      school: 'Void',
      color: '#8a68e8',
      core: '#d6c8ff',
      position: { x: 0.68, y: 0.34 },
      sequence: ['voidNova', 'shadowBeam'],
    },
  },
  mechanics: {
    solarLance: {
      name: 'Solar Lance',
      castTime: 1.8,
      damage: 38,
      range: 650,
      halfAngle: 0.28,
    },
    solarFlare: {
      name: 'Solar Flares',
      castTime: 2.0,
      damage: 32,
      count: 4,
      radius: 72,
      delay: 1.25,
      spread: 340,
    },
    voidNova: {
      name: 'Void Collapse',
      castTime: 1.9,
      damage: 42,
      radius: 265,
    },
    shadowBeam: {
      name: 'Shadow Sweep',
      castTime: 1.7,
      damage: 18,
      duration: 3.1,
      length: 760,
      halfWidth: 25,
      rotationSpeed: 1.35,
      hitCooldown: 0.7,
    },
  },
  finalPairs: [
    ['solarLance', 'voidNova'],
    ['solarFlare', 'shadowBeam'],
    ['solarLance', 'shadowBeam'],
    ['solarFlare', 'voidNova'],
  ],
};
